# Site settings
title: (\x -> "Blog")
email: jsnider3@masonlive.gmu.edu
description: "An attempt at a blog by someone who thinks Haskell is cool."
baseurl: ""
url: "http://jsnider3.github.io"

# Build settings
markdown: kramdown
permalink: pretty
