runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /api/.*
  script: main.app

- url: /
  static_files: src/_site/index.html
  upload: src/_site/index.html

- url: /(.*)/
  static_files: src/_site/\1/index.html
  upload: src/_site/*.*

- url: /(.*)
  static_files: src/_site/\1
  upload: src/_site/(.*)

error_handlers:
- file: src/_site/404.html
