runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /
  static_files: src/_site/index.html
  upload: src/_site/index.html

- url: /update/(.*)/
  static_files: src/_site/update/\1/index.html
  upload: src/_site/*.*

- url: /update/(.*)/
  static_files: src/_site/update/\1/index.html
  upload: src/_site/*.*

- url: /css/(.*)
  static_files: src/_site/css/\1
  upload: src/_site/*.*

- url: /js/(.*)
  static_files: src/_site/js/\1
  upload: src/_site/*.*

- url: /QuisCustodiet/
  static_files: src/_site/QuisCustodiet/index.html
  upload: src/_site/(.*)

- url: /about/
  static_files: src/_site/about/index.html
  upload: src/_site/(.*)

- url: /.*
  script: main.app

