runtime: python27
api_version: 1
version: 1
threadsafe: yes

handlers:

- url: /api/.*
  script: main.app

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /(.*)/
  static_files: static/\1/index.html
  upload: static/*.*

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)

error_handlers:
- file: static/404.html
